### ISSUE TITLE
Friend System Progress

### ISSUE THREAD

**Issue by lukechatton** [weeco/fortnite-client#11]
Is there a time frame for when you think the friend and messaging systems will be implemented? This would be huge for the project.

**Comment by weeco** [comment]
I am currently on holidays. Before I went on holidays I looked into a way to bypass the ssl pinning. Luckily epic games doesn't use ssl pinning for the launcher yet, hence it should be easy to figure out the endpoints.

I'll be back in the mid of June and I will work on these endpoints then.

**Comment by lukechatton** [comment]
Looking forward to that! Great repo.

**Comment by weeco** [comment]
@lukechatton I added the launcher client, however I noticed there is no websocket or long polling HTTPS communication for incoming friend requests. It seems the launcher is using some custom TCP protocol additionally, to get these real time events. I expected them to use Websockets.

I am not sure if I can figure that out, but I'll try to.

**Comment by weeco** [comment]
They communicate via Port 5222 using the jabber client (XMPP protocol). Communication is TLS encrypted

**Comment by leomelki** [comment]
Did you find anything ? Or do you have any idea on how to bypass/decrypt this TLS encryption please ?

**Comment by weeco** [comment]
@leomelki Yes, I figured something out, but currently I don't have time to further investigate. I hope to have something ready to release within the next 2 month.

**Comment by leomelki** [comment]
Can you please tell me what you found (code if possible), I can reverse the protocol. I'm just having troubles with authentification and I don't see how to mitm the TLS encrypted connection.
Thank you

**Comment by weeco** [comment]
@leomelki Currently I don't want to share how you can bypass the SSL pinning, so that you can inject your own certificates and decrypt the traffic as Epic seems to watch some Github repositories. Multiple workarounds have already been patched by Epic.
