### ISSUE TITLE
PvE endpoints

### ISSUE THREAD

**Issue by maxifn** [weeco/fortnite-client#17]
Hi! Thank you for this library!
Do you have any plans for adding Save The World related endpoints (available missions/etc)?

**Comment by weeco** [comment]
Hi,
I don't have access to the PvE mode of this game, but I haven't seen them in any responses (except news and game status). You would need to reverse engineer them on your own, then you can create a PR.

**Comment by maxifn** [comment]
Any idea how I can capture traffic assuming Fortnite uses certificate pinning?

**Comment by weeco** [comment]
I am afraid I don't want to share it as the last workaround to bypass it has been patched quite quickly by Epic Games. They are probably watching out for all the bypasses trying to make it harder to reverse engineer.
