### ISSUE TITLE
Remove codecov ignores

### ISSUE THREAD

**Issue by weeco** [weeco/fortnite-client#9]
Telling istanbul to ignore these cases for codevoerage doesn't make sense and should be removed, for instance here: https://github.com/weeco/fortnite-client/blob/develop/src/fortnite-client.ts .

**Comment by atjeff** [comment]
@weeco do you just need someone to run through and remove the istanbul ignores?

**Comment by weeco** [comment]
@atjeff Basically yes, check the codecov ignores and then remove it if it does make sense to write a test for it :-).

**Comment by atjeff** [comment]
@weeco It looks like the src/*.ts files are being ignored by the nyc coverage is this intended?
